### PR TITLE
Redesign to allow storage methods customization

### PR DESCRIPTION
**Pull request by anddrzejb**
This is a major redesign proposal. I will try to point out the changes:
1. Samples were restructured - shared code has been extracted to shared project, 2 new sample projects for blazor server version.  
2. Store handling has been extracted to classes that implement `IStoreHandler`. In the project there are 2 classes that implement it:
   - `JsonStoreHandler.cs` - this is the previous code that was in `PersistMiddleware` and was responsible for state to json serialization and json to state deserialization; it contains a store of type `IStringStateStorage` (sample implementation is in sample shared project `LocalStateStorage.cs`)
   - `DictionaryStoreHandler` (the name probably should be changed to more generic) - this store just passes the state to store of type `IObjectStateStorage` (sample implementation is in sample shared project `InMemoryStateStorage.cs`)

3. Store handlers and stores are added to DI in `Startup.cs` and `Program.cs` (depending on the hosting model)
4. White/black lists are based on dictionaries. Also consumers can use `IPreserveState` / `ISkipPreserveState` marker interfaces on states, to apply desired persist behaviour. The model was kept - either use exclusion approach (default) where `ISkipPresreveState` & black list is checked or use inclusion approach where `IPresreveState` & white list is checked. I left the white/black lists for 2 reasons: 
   a) mandatory black list
   b) it is much easier to extend the package in the future and open ability to include/exclude state during program flow
5. There are couple of simple examples of how the include/exclude approach is working - play around with the commented section in `Startup.cs`/`Program.cs` .
6. `InitializePersistMiddlewareAction.cs` and reducer has been removed, as I do not see any need for it any longer.

In server version, before state is restored from storage, the initial values are visible (fraction of a second, but this is noticable). This can be solved with injecting preserving store to feature and provide initial value from the store (if exists). But because this is not yet really sanctioned as a correct approach, I kept it out of this solution.

### CODE REVIEW

**Comment by Tailslide** [comment]
Just adding some more info here about initial state.. this is how redux-persist initialization looks like.. @@INIT to default state, a PERSIST state where it initializes the persist middleware and a rehydrate state.  Some of the reasons for how they do things might not apply but there also may be good ideas worth stealing there.

https://github.com/rt2zz/redux-persist


image

**Comment by Tailslide** [comment]
I had a look through it looks like a lot of work!

Would it be ok with you to use attributes instead of adding the empty interface IPersistState to the states?
I like the idea of not imposing requirements on the state objects.

Also, changing from ISyncLocalStorageService to  ILocalStorageService seems to have caused some side effects in the WASM sample where it's not drawing correctly.. changing it back seems to fix it so I checked in this change:

image

**Review by anddrzejb — COMMENTED** [review]
Right....my bad. Seems that the code for pages cannot be really shared then. When running server version, async **has** to be used, otherwise it will not work. Unless you tell me what kind of issues you were experiencing - maybe they can be fixed without sacrificing the sharing of components?
Or I can add a piece of code that will check for blazor wasm and either get service from `ServiceProvider` or inject both and decide which to use....
Attributes - I will have a look at that.

**Comment by Tailslide** [comment]
> Right....my bad. Seems that the code for pages cannot be really shared then. When running server version, async **has** to be used, otherwise it will not work. Unless you tell me what kind of issues you were experiencing - maybe they can be fixed without sacrificing the sharing of components?

It seems like it should be possible to make it work on both I wasn't aware that it has to be async for the server version.   I'll have another go at getting the client to refresh OK async.  You can see the issue in the screenshot showing on my previous comment.

**Comment by anddrzejb** [comment]
Yeah, I have it on mine as well. What I found out is basically that the last `SubscribeToAction` fails to render. If you change the order, you will notice that.
Edit: actually, it is not `SubscribeToAction` but the `CountFromStore` dictionary order...

**Comment by anddrzejb** [comment]
So, if you add `StateHasChanged()`, then it is going to show it...
```csharp
        protected override async Task OnAfterRenderAsync(bool firstRender)
        {
            if (firstRender)
            {
                CounterFromStore["Counter"] = await localStorage.GetItemAsStringAsync("Counter");
                CounterFromStore["CounterInclude"] = await localStorage.GetItemAsStringAsync("CounterInclude");
                CounterFromStore["CounterExclude"] = await localStorage.GetItemAsStringAsync("CounterExclude");

                SubscribeToAction((Action<IncrementCounterAction>)(result => PrintStateDirectly("Counter")));
                SubscribeToAction((Action<IncrementCounterIncludeAction>)(result => PrintStateDirectly("CounterInclude")));
                SubscribeToAction((Action<IncrementCounterExcludeAction>)(result => PrintStateDirectly("CounterExclude")));
                StateHasChanged();
            }
            await base.OnAfterRenderAsync(firstRender);
        }
```

**Comment by Tailslide** [comment]
Good call.. I reverted my change and added that.

**Pull request merged**
